server:
  port: 8085

spring:
  datasource:
    #使用8以上的mysql，如果是低等级的mysql，请改为com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver

    #上线时需改成云数据库或本地数据库设置的地址
    url: jdbc:mysql://localhost:3306/togethertime?serverTimezone=UTC
    #数据库密码
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
