server:
  port: 8085

spring:
  datasource:
    username: root
    #到时候记得改密码
#    password: toGetherTime565
    #使用8以上的mysql，如果是低等级的mysql，请改为com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #上线时需改成云数据库或本地数据库设置的地址
    url: jdbc:mysql://localhost:3306/togethertime?serverTimezone=UTC
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
